image: ondrejsika/ci

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  TEST_CONTAINER_NAME: test-$CI_JOB_ID

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

go format check:
  image: golang:1.14
  stage: lint
  script:
    - diff -u <(echo -n) <(gofmt -d ./)

editorconfig check:
  image: mstruebing/editorconfig-checker
  stage: lint
  script:
    - ec

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

test:
  stage: test
  script:
    - docker run --name $TEST_CONTAINER_NAME -d $IMAGE
    - sleep 5
    - docker run --rm --link $TEST_CONTAINER_NAME nixery.dev/curl curl -sSL $TEST_CONTAINER_NAME
  after_script:
    - docker stop $TEST_CONTAINER_NAME
    - docker rm $TEST_CONTAINER_NAME
