image: ondrejsika/ci

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  TEST_CONTAINER_NAME: test-$CI_JOB_ID
  DEPLOY_NAME: example-$CI_COMMIT_REF_SLUG
  DEPLOY_NAME_PROD: example-prod

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

go format check:
  image: golang:1.14
  stage: lint
  script:
    - diff -u <(echo -n) <(gofmt -d ./)

editorconfig check:
  image: mstruebing/editorconfig-checker
  stage: lint
  script:
    - ec

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

test:
  stage: test
  script:
    - docker network create $TEST_CONTAINER_NAME
    - docker run --name $TEST_CONTAINER_NAME --net $TEST_CONTAINER_NAME -d $IMAGE
    - sleep 5
    - docker run --rm --net $TEST_CONTAINER_NAME nixery.dev/curl curl -sSL $TEST_CONTAINER_NAME
  after_script:
    - docker stop $TEST_CONTAINER_NAME
    - docker rm $TEST_CONTAINER_NAME
    - docker network rm $TEST_CONTAINER_NAME

deploy dev:
  stage: deploy dev
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install
      $DEPLOY_NAME ondrejsika/one-image
      --set image=$IMAGE
      --set host=$DEPLOY_NAME.$BASE_DOMAIN
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$DEPLOY_NAME.$BASE_DOMAIN
    on_stop: stop dev

stop dev:
  stage: deploy dev
  when: manual
  script:
    - helm uninstall $DEPLOY_NAME
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop

deploy prod:
  stage: deploy prod
  script:
    - helm repo add ondrejsika https://helm.oxs.cz
    - helm upgrade --install
      ondrejsika/one-image
      --set image=$IMAGE
      --set host=prod.$BASE_DOMAIN
  environment:
    name: prod
    url: https://prod.$BASE_DOMAIN
